### ISSUE TITLE
安卓SDL build失败 

### ISSUE THREAD

**Issue by guotong1988** [sdlpal/sdlpal#182]
报错信息：
```
armeabi-v7a] Compile thumb  : main <= stream.c
[armeabi-v7a] Compile thumb  : main <= synth.c
[armeabi-v7a] Compile thumb  : main <= timer.c
[armeabi-v7a] Compile thumb  : main <= native_midi_common.c
[armeabi-v7a] Compile++ thumb: main <= android_jni.cpp
[armeabi-v7a] Compile thumb  : main <= native_midi.c
[armeabi-v7a] SharedLibrary  : libmain.so

fatal: No names found, cannot describe anything.
```

```

make: *** [C:/Users/gt/Desktop/xianjian/sdlpal/android/app/build/intermediates/ndkBuild/debug/obj/local/armeabi-v7a/libmain.so] Error 87

	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:79)
	at com.android.build.gradle.internal.cxx.process.ProcessOutputJunction.execute(ProcessOutputJunction.kt:120)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.executeProcessBatch(ExternalNativeBuildTask.java:471)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.buildImpl(ExternalNativeBuildTask.java:207)
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.doTaskAction(ExternalNativeBuildTask.java:107)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:51)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask$taskAction$$inlined$recordTaskAction$1.invoke(AndroidVariantTask.kt:31)
	at com.android.build.gradle.internal.tasks.Blocks.recordSpan(Blocks.java:91)
	at com.android.build.gradle.internal.tasks.NonIncrementalTask.taskAction(NonIncrementalTask.kt:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
	... 186 more

```

**Comment by guotong1988** [comment]
NDK版本不对？

**Comment by guotong1988** [comment]
完整报错信息
```
Build command failed.
Error while executing process C:\CCZ\android-ndk-r20b\ndk-build.cmd with arguments {NDK_PROJECT_PATH=null APP_BUILD_SCRIPT=C:\Users\gt\Desktop\xianjian\sdlpal\android\app\src\main\cpp\Android.mk NDK_APPLICATION_MK=C:\Users\gt\Desktop\xianjian\sdlpal\android\app\src\main\cpp\Application.mk APP_ABI=arm64-v8a NDK_ALL_ABIS=arm64-v8a NDK_DEBUG=1 APP_PLATFORM=android-16 NDK_OUT=C:/Users/gt/Desktop/xianjian/sdlpal/android/app/build/intermediates/ndkBuild/debug/obj NDK_LIBS_OUT=C:\Users\gt\Desktop\xianjian\sdlpal\android\app\build\intermediates\ndkBuild\debug\lib NDK_APPLICATION_MK:=src/main/cpp/Application.mk C:/Users/gt/Desktop/xianjian/sdlpal/android/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/libmain.so}
[arm64-v8a] Compile        : main <= SDL_android_main.c
[arm64-v8a] Compile++      : main <= rixplay.cpp
[arm64-v8a] Compile        : main <= audio.c
[arm64-v8a] Compile        : main <= aviplay.c
[arm64-v8a] Compile        : main <= battle.c
[arm64-v8a] Compile        : main <= ending.c
[arm64-v8a] Compile        : main <= fight.c
[arm64-v8a] Compile        : main <= font.c
[arm64-v8a] Compile        : main <= game.c
[arm64-v8a] Compile        : main <= global.c
[arm64-v8a] Compile        : main <= glslp.c
[arm64-v8a] Compile        : main <= input.c
[arm64-v8a] Compile        : main <= itemmenu.c
[arm64-v8a] Compile        : main <= magicmenu.c
[arm64-v8a] Compile        : main <= main.c
[arm64-v8a] Compile        : main <= map.c
[arm64-v8a] Compile        : main <= midi.c
[arm64-v8a] Compile        : main <= mini_glloader.c
[arm64-v8a] Compile        : main <= mp3play.c
[arm64-v8a] Compile        : main <= oggplay.c
[arm64-v8a] Compile        : main <= opusplay.c
[arm64-v8a] Compile        : main <= overlay.c
[arm64-v8a] Compile        : main <= palcfg.c
[arm64-v8a] Compile        : main <= palcommon.c
[arm64-v8a] Compile        : main <= palette.c
[arm64-v8a] Compile        : main <= play.c
[arm64-v8a] Compile        : main <= res.c
[arm64-v8a] Compile        : main <= resampler.c
[arm64-v8a] Compile        : main <= rngplay.c
[arm64-v8a] Compile        : main <= scene.c
[arm64-v8a] Compile        : main <= script.c
[arm64-v8a] Compile        : main <= sound.c
[arm64-v8a] Compile        : main <= text.c
[arm64-v8a] Compile        : main <= ui.c
[arm64-v8a] Compile        : main <= uibattle.c
[arm64-v8a] Compile        : main <= uigame.c
[arm64-v8a] Compile        : main <= util.c
[arm64-v8a] Compile        : main <= video.c
[arm64-v8a] Compile        : main <= video_glsl.c
[arm64-v8a] Compile        : main <= yj1.c
[arm64-v8a] Compile        : main <= nuked_opl.c
[arm64-v8a] Compile++      : main <= binfile.cpp
[arm64-v8a] Compile++      : main <= binio.cpp
[arm64-v8a] Compile++      : main <= dosbox_opls.cpp
[arm64-v8a] Compile++      : main <= emuopls.cpp
[arm64-v8a] Compile++      : main <= fprovide.cpp
[arm64-v8a] Compile++      : main <= mame_opls.cpp
[arm64-v8a] Compile++      : main <= player.cpp
[arm64-v8a] Compile++      : main <= rix.cpp
[arm64-v8a] Compile++      : main <= surroundopl.cpp
[arm64-v8a] Compile        : main <= http.c
[arm64-v8a] Compile        : main <= internal.c
[arm64-v8a] Compile        : main <= mapping_matrix.c
[arm64-v8a] Compile        : main <= mlp.c
[arm64-v8a] Compile        : main <= mlp_data.c
[arm64-v8a] Compile        : main <= opus.c
[arm64-v8a] Compile        : main <= opus_analysis.c
[arm64-v8a] Compile        : main <= opus_decoder.c
[arm64-v8a] Compile        : main <= opus_encoder.c
[arm64-v8a] Compile        : main <= opus_info.c
[arm64-v8a] Compile        : main <= opus_multistream.c
[arm64-v8a] Compile        : main <= opus_multistream_decoder.c
[arm64-v8a] Compile        : main <= opus_multistream_encoder.c
[arm64-v8a] Compile        : main <= opus_projection_decoder.c
[arm64-v8a] Compile        : main <= opus_projection_encoder.c
[arm64-v8a] Compile        : main <= opus_stream.c
[arm64-v8a] Compile        : main <= opusfile.c
[arm64-v8a] Compile        : main <= repacketizer.c
[arm64-v8a] Compile        : main <= wincerts.c
[arm64-v8a] Compile        : main <= bands.c
[arm64-v8a] Compile        : main <= celt.c
[arm64-v8a] Compile        : main <= celt_decoder.c
[arm64-v8a] Compile        : main <= celt_encoder.c
[arm64-v8a] Compile        : main <= celt_lpc.c
[arm64-v8a] Compile        : main <= cwrs.c
[arm64-v8a] Compile        : main <= entcode.c
[arm64-v8a] Compile        : main <= entdec.c
[arm64-v8a] Compile        : main <= entenc.c
[arm64-v8a] Compile        : main <= kiss_fft.c
[arm64-v8a] Compile        : main <= laplace.c
[arm64-v8a] Compile        : main <= mathops.c
[arm64-v8a] Compile        : main <= modes.c
[arm64-v8a] Compile        : main <= opus_mdct.c
[arm64-v8a] Compile        : main <= pitch.c
[arm64-v8a] Compile        : main <= quant_bands.c
[arm64-v8a] Compile        : main <= rate.c
[arm64-v8a] Compile        : main <= vq.c
[arm64-v8a] Compile        : main <= A2NLSF.c
[arm64-v8a] Compile        : main <= CNG.c
[arm64-v8a] Compile        : main <= HP_variable_cutoff.c
[arm64-v8a] Compile        : main <= LPC_analysis_filter.c
[arm64-v8a] Compile        : main <= LPC_fit.c
[arm64-v8a] Compile        : main <= LPC_inv_pred_gain.c
[arm64-v8a] Compile        : main <= LP_variable_cutoff.c
[arm64-v8a] Compile        : main <= NLSF2A.c
[arm64-v8a] Compile        : main <= NLSF_VQ.c
[arm64-v8a] Compile        : main <= NLSF_VQ_weights_laroia.c
[arm64-v8a] Compile        : main <= NLSF_decode.c
[arm64-v8a] Compile        : main <= NLSF_del_dec_quant.c
[arm64-v8a] Compile        : main <= NLSF_encode.c
[arm64-v8a] Compile        : main <= NLSF_stabilize.c
[arm64-v8a] Compile        : main <= NLSF_unpack.c
[arm64-v8a] Compile        : main <= NSQ.c
[arm64-v8a] Compile        : main <= NSQ_del_dec.c
[arm64-v8a] Compile        : main <= PLC.c
[arm64-v8a] Compile        : main <= VAD.c
[arm64-v8a] Compile        : main <= VQ_WMat_EC.c
[arm64-v8a] Compile        : main <= ana_filt_bank_1.c
[arm64-v8a] Compile        : main <= biquad_alt.c
[arm64-v8a] Compile        : main <= bwexpander.c
[arm64-v8a] Compile        : main <= bwexpander_32.c
[arm64-v8a] Compile        : main <= check_control_input.c
[arm64-v8a] Compile        : main <= code_signs.c
[arm64-v8a] Compile        : main <= control_SNR.c
[arm64-v8a] Compile        : main <= control_audio_bandwidth.c
[arm64-v8a] Compile        : main <= control_codec.c
[arm64-v8a] Compile        : main <= debug.c
[arm64-v8a] Compile        : main <= dec_API.c
[arm64-v8a] Compile        : main <= decode_core.c
[arm64-v8a] Compile        : main <= decode_frame.c
[arm64-v8a] Compile        : main <= decode_indices.c
[arm64-v8a] Compile        : main <= decode_parameters.c
[arm64-v8a] Compile        : main <= decode_pitch.c
[arm64-v8a] Compile        : main <= decode_pulses.c
[arm64-v8a] Compile        : main <= decoder_set_fs.c
[arm64-v8a] Compile        : main <= enc_API.c
[arm64-v8a] Compile        : main <= encode_indices.c
[arm64-v8a] Compile        : main <= encode_pulses.c
[arm64-v8a] Compile        : main <= gain_quant.c
[arm64-v8a] Compile        : main <= init_decoder.c
[arm64-v8a] Compile        : main <= init_encoder.c
[arm64-v8a] Compile        : main <= inner_prod_aligned.c
[arm64-v8a] Compile        : main <= interpolate.c
[arm64-v8a] Compile        : main <= lin2log.c
[arm64-v8a] Compile        : main <= log2lin.c
[arm64-v8a] Compile        : main <= opus_resampler.c
[arm64-v8a] Compile        : main <= pitch_est_tables.c
[arm64-v8a] Compile        : main <= process_NLSFs.c
[arm64-v8a] Compile        : main <= quant_LTP_gains.c
[arm64-v8a] Compile        : main <= resampler_down2.c
[arm64-v8a] Compile        : main <= resampler_down2_3.c
[arm64-v8a] Compile        : main <= resampler_private_AR2.c
[arm64-v8a] Compile        : main <= resampler_private_IIR_FIR.c
[arm64-v8a] Compile        : main <= resampler_private_down_FIR.c
[arm64-v8a] Compile        : main <= resampler_private_up2_HQ.c
[arm64-v8a] Compile        : main <= resampler_rom.c
[arm64-v8a] Compile        : main <= shell_coder.c
[arm64-v8a] Compile        : main <= sigm_Q15.c
[arm64-v8a] Compile        : main <= sort.c
[arm64-v8a] Compile        : main <= stereo_LR_to_MS.c
[arm64-v8a] Compile        : main <= stereo_MS_to_LR.c
[arm64-v8a] Compile        : main <= stereo_decode_pred.c
[arm64-v8a] Compile        : main <= stereo_encode_pred.c
[arm64-v8a] Compile        : main <= stereo_find_predictor.c
[arm64-v8a] Compile        : main <= stereo_quant_pred.c
[arm64-v8a] Compile        : main <= sum_sqr_shift.c
[arm64-v8a] Compile        : main <= table_LSF_cos.c
[arm64-v8a] Compile        : main <= tables_LTP.c
[arm64-v8a] Compile        : main <= tables_NLSF_CB_NB_MB.c
[arm64-v8a] Compile        : main <= tables_NLSF_CB_WB.c
[arm64-v8a] Compile        : main <= tables_gain.c
[arm64-v8a] Compile        : main <= tables_other.c
[arm64-v8a] Compile        : main <= tables_pitch_lag.c
[arm64-v8a] Compile        : main <= tables_pulses_per_block.c
[arm64-v8a] Compile        : main <= LPC_analysis_filter_FLP.c
[arm64-v8a] Compile        : main <= LPC_inv_pred_gain_FLP.c
[arm64-v8a] Compile        : main <= LTP_analysis_filter_FLP.c
[arm64-v8a] Compile        : main <= LTP_scale_ctrl_FLP.c
[arm64-v8a] Compile        : main <= apply_sine_window_FLP.c
[arm64-v8a] Compile        : main <= autocorrelation_FLP.c
[arm64-v8a] Compile        : main <= burg_modified_FLP.c
[arm64-v8a] Compile        : main <= bwexpander_FLP.c
[arm64-v8a] Compile        : main <= corrMatrix_FLP.c
[arm64-v8a] Compile        : main <= encode_frame_FLP.c
[arm64-v8a] Compile        : main <= energy_FLP.c
[arm64-v8a] Compile        : main <= find_LPC_FLP.c
[arm64-v8a] Compile        : main <= find_LTP_FLP.c
[arm64-v8a] Compile        : main <= find_pitch_lags_FLP.c
[arm64-v8a] Compile        : main <= find_pred_coefs_FLP.c
[arm64-v8a] Compile        : main <= inner_product_FLP.c
[arm64-v8a] Compile        : main <= k2a_FLP.c
[arm64-v8a] Compile        : main <= noise_shape_analysis_FLP.c
[arm64-v8a] Compile        : main <= pitch_analysis_core_FLP.c
[arm64-v8a] Compile        : main <= process_gains_FLP.c

fatal: No names found, cannot describe anything.
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../text.c:1510:13: warning: add explicit braces to avoid dangling else [-Wdangling-else]
            else
            ^
1 warning generated.
In file included from C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox_opls.cpp:46:
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:846:10: warning: no case matching constant switch condition '11'
        switch( mode ) {
                ^~~~
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:1033:38: note: in instantiation of function template specialization 'DBOPL::Channel::BlockTemplate<DBOPL::sm3Percussion>' requested here
                                chan[6].synthHandler = &Channel::BlockTemplate< sm3Percussion >; 
                                                                 ^
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:936:11: warning: no case matching constant switch condition '11'
                switch( mode ) {
                        ^~~~
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:846:10: warning: no case matching constant switch condition '10'
        switch( mode ) {
                ^~~~
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:1035:38: note: in instantiation of function template specialization 'DBOPL::Channel::BlockTemplate<DBOPL::sm2Percussion>' requested here
                                chan[6].synthHandler = &Channel::BlockTemplate< sm2Percussion >; 
                                                                 ^
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../adplug/dosbox/dbopl.cpp.h:936:11: warning: no case matching constant switch condition '10'
                switch( mode ) {
                        ^~~~
4 warnings generated.
C:/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/../../../../../libopusfile/src/opus_decoder.c:37:10: warning: You appear to be compiling without optimization, if so opus will be very slow. [-W#pragma-messages]
# pragma message "You appear to be compiling without optimization, if so opus will be very slow."
         ^
1 warning generated.
�ܾ����ʡ�
make: *** [C:/Users/gt/Desktop/xianjian/sdlpal/android/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/objs-debug/main/C_/Users/gt/Desktop/xianjian/sdlpal/android/app/src/main/cpp/__/__/__/__/__/libopusfile/silk/float/regularize_correlations_FLP.o] Error 1

```

**Comment by guotong1988** [comment]
NDK版本不对？

**Comment by PalMusicFan** [comment]
目录的路径太长了，放在分区根目录编译。
